apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-spot-termination-notice-handler
  name: kube-spot-termination-notice-handler
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-spot-termination-notice-handler
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-spot-termination-notice-handler
    spec:
      containers:
      - image: hoppinger/kube-spot-termination-notice-handler:1.11.3-1
        imagePullPolicy: IfNotPresent
        name: kube-spot-termination-notice-handler
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # resources:
        #   limits:
        #     memory: 200Mi
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        # securityContext:
        #   runAsUser: 0
      nodeSelector:
        on-demand: "false"
      tolerations:
      - effect: NoSchedule
        operator: Exists